# Sepcification for webpage paths
openapi: 3.0.0
info:
  version: 1.0.0
  title: VV8Web
  description: Webpage endpoint specifications
servers:
- url: http://localhost:{port}
  description: Local host debugging server
  variables:
    port:
      default: '8080'
paths:
  /:
    get:
      description: Returns home page for VV8 Web
      operationId: webpage.get_root
      responses:
        200:
          $ref: '#/components/responses/webpage'
        default:
          description: Unexpected error
  /test:
    get:
      description: Test webpage
      operationId: webpage.get_test
      responses:
        200:
          $ref: '#/components/responses/webpage'
        default:
          description: Unexpected error
components:
  responses:
    webpage:
      description: Webpage
      content:
        text/html:
          schema:
            type: string
