version: "3.9"
services:
  web_server:
    image: vv8web
    build:
      context: ./web_server
      dockerfile: Dockerfile
    ports:
      - "8080:80/tcp"
  database:
    image: vv8db
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - vv8db:/var/lib/postgresql/data
  task_queue_broker:
    image: redis:6.2
  vv8_worker:
    # Processes urls using vv8
    build:
      context: ./task_queue
      dockerfile: vv8_worker.dockerfile
    image: vv8web_vv8_worker
    environment:
      VV8_CELERY_BROKER: task_queue_broker
      VV8_CELERY_BROKER_PORT: 6379
      VV8_CELERY_ID: vv8_worker
volumes:
  vv8db: {}
