version: "3.9"
services:
  web_server:
    image: vv8web
    build:
      context: ./web_server
      dockerfile: Dockerfile
    ports:
      - "8080:80/tcp"
  database:
    image: vv8db
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5432:5432/tcp"
    volumes:
      - vv8db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
volumes:
  vv8db: {}
