version: "3.9"
services:
  web_server:
    image: vv8web
    build:
      context: ./web_server
      dockerfile: Dockerfile
    ports:
      - "8080:80/tcp"
  database:
    image: vv8db
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - vv8db:/var/lib/postgresql/data
  task_queue_broker:
    image: redis:6.2
  task_queue_test_worker:
    # This is just a test worker as a proof of concept
    build:
      context: ./task_queue
      dockerfile: test_worker.dockerfile
    image: vv8web_task_queue_test_worker
    environment:
      VV8_CELERY_BROKER: task_queue_broker
      VV8_CELERY_BROKER_PORT: 6379
      VV8_CELERY_ID: test_worker
  task_queue_tester:
    # This image loops creating test tasks
    build:
      context: ./task_queue
      dockerfile: test_worker.dockerfile
    entrypoint: "python3 ./vv8web_task_queue/schedule.py"
    environment:
      VV8_CELERY_BROKER: task_queue_broker
      VV8_CELERY_BROKER_PORT: 6379
      VV8_CELERY_ID: test_task
volumes:
  vv8db: {}
