version: "3.9"
services:
  web_server:
    image: vv8web
    build:
      context: .
      dockerfile: web_server.dockerfile
    ports:
      - "8080:80/tcp"
    environment:
      VV8_CELERY_BROKER: task_queue_broker
      VV8_CELERY_BROKER_PORT: 6379
      VV8_CELERY_ID: vv8_web_server
  database:
    image: vv8db
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - vv8db:/var/lib/postgresql/data
  database_sidecar:
    image: vv8db_sidecar
    build:
      context: ./database_sidecar
      dockerfile: Dockerfile
  task_queue_broker:
    image: redis:6.2
  vv8_worker:
    build:
      context: ./task_queue
      dockerfile: vv8_worker.dockerfile
    image: vv8web_vv8_worker
    environment:
      VV8_CELERY_BROKER: task_queue_broker
      VV8_CELERY_BROKER_PORT: 6379
      VV8_CELERY_ID: vv8_worker
  log_parser:
    build:
      context: ./task_queue
      dockerfile: ./log_parser.dockerfile
    image: vv8web_log_parser
    environment:
      VV8_CELERY_BROKER: task_queue_broker
      VV8_CELERY_BROKER_PORT: 6379
      VV8_CELERY_ID: vv8_log_parser
volumes:
  vv8db: {}
